import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { readCharacters } from '@/lib/characters.server';
import { readWorkshop } from '@/lib/workshop.server';
import archiver from 'archiver';

export const maxDuration = 120;

function parseCharacterId(raw: string): number | null {
  const n = Number(raw);
  return Number.isFinite(n) && n > 0 ? n : null;
}

const BASE = process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000';

async function fetchBuffer(url: string): Promise<Buffer> {
  const full = url.startsWith('http') ? url : `${BASE}${url}${url.includes('?') ? '&' : '?'}w=2000`;
  const res = await fetch(full);
  if (!res.ok) throw new Error(`Fetch ${full}: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

export async function GET(_req: NextRequest, { params }: { params: Promise<{ characterId: string }> }) {
  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { characterId: raw } = await params;
  const characterId = parseCharacterId(raw);
  if (!characterId) return NextResponse.json({ error: 'Invalid characterId' }, { status: 400 });

  const characters = await readCharacters();
  const character = characters.find((c) => c.id === characterId);
  if (!character) return NextResponse.json({ error: 'Character not found' }, { status: 404 });

  const workshop = await readWorkshop(userId, characterId);
  const slug = character.slug;

  // Stream a zip
  const archive = archiver('zip', { zlib: { level: 5 } });
  const chunks: Uint8Array[] = [];
  archive.on('data', (chunk: Uint8Array) => chunks.push(chunk));

  const done = new Promise<Buffer>((resolve, reject) => {
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);
  });

  // Profile
  try {
    const buf = await fetchBuffer(character.img);
    archive.append(buf, { name: `${slug}-profile.jpg` });
  } catch {}

  // Reference sheet
  if (character.referenceSheetUrl) {
    try {
      const buf = await fetchBuffer(character.referenceSheetUrl);
      archive.append(buf, { name: `${slug}-reference-sheet.jpg` });
    } catch {}
  }

  // Outfits
  for (let i = 0; i < workshop.outfits.length; i++) {
    try {
      const buf = await fetchBuffer(workshop.outfits[i].imageUrl);
      archive.append(buf, { name: `wardrobe/${slug}-outfit-${i + 1}.jpg` });
    } catch {}
  }

  // Scenes
  for (let i = 0; i < workshop.shots.length; i++) {
    try {
      const buf = await fetchBuffer(workshop.shots[i].imageUrl);
      archive.append(buf, { name: `scenes/${slug}-scene-${i + 1}.jpg` });
    } catch {}
  }

  // README
  const readme = `# ${character.name} — Cast Character Package

## Contents
- ${slug}-profile.jpg — Profile headshot (2K)
${character.referenceSheetUrl ? `- ${slug}-reference-sheet.jpg — 4K 8-panel reference sheet\n` : ''}- wardrobe/ — ${workshop.outfits.length} outfit variant(s)
- scenes/ — ${workshop.shots.length} scene shot(s)

## How to use

### Kling 3.0 Pro
1. Open Kling → Image to Video
2. Upload the profile or any outfit/scene image as the starting frame
3. Describe the action in your prompt
4. For character consistency across shots, use the reference sheet panels as references

### Runway Gen-4
1. Open Runway → Image to Video
2. Upload any image from this package
3. The reference sheet ensures the same face across every generation

### Veo 3.1
1. Open Veo → Image to Video
2. Upload the profile or scene image
3. Describe the motion — Veo preserves identity from the reference frame

## License
Generated by Cast (castability.ai). Please check your license tier for usage rights.
`;
  archive.append(Buffer.from(readme, 'utf-8'), { name: 'README.md' });

  archive.finalize();
  const zipBuffer = await done;

  return new NextResponse(new Uint8Array(zipBuffer), {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${slug}-cast-package.zip"`,
    },
  });
}
