import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { readCustomWorkshop } from '@/lib/custom-workshop.server';
import archiver from 'archiver';

export const maxDuration = 120;

const BASE = process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000';

async function fetchBuffer(url: string): Promise<Buffer> {
  const full = url.startsWith('http') ? url : `${BASE}${url}${url.includes('?') ? '&' : '?'}w=2000`;
  const res = await fetch(full);
  if (!res.ok) throw new Error(`Fetch ${full}: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;
  const workshop = await readCustomWorkshop(userId, id);
  if (!workshop) return NextResponse.json({ error: 'Workshop not found' }, { status: 404 });

  const slug = workshop.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');

  const archive = archiver('zip', { zlib: { level: 5 } });
  const chunks: Uint8Array[] = [];
  archive.on('data', (chunk: Uint8Array) => chunks.push(chunk));

  const done = new Promise<Buffer>((resolve, reject) => {
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);
  });

  // Source image
  try {
    const buf = await fetchBuffer(workshop.sourceImageUrl);
    archive.append(buf, { name: `${slug}-source.jpg` });
  } catch {}

  // Outfits
  for (let i = 0; i < workshop.outfits.length; i++) {
    try {
      const buf = await fetchBuffer(workshop.outfits[i].imageUrl);
      archive.append(buf, { name: `wardrobe/${slug}-outfit-${i + 1}.jpg` });
    } catch {}
  }

  // Scenes
  for (let i = 0; i < workshop.shots.length; i++) {
    try {
      const buf = await fetchBuffer(workshop.shots[i].imageUrl);
      archive.append(buf, { name: `scenes/${slug}-scene-${i + 1}.jpg` });
    } catch {}
  }

  // README
  const readme = `# ${workshop.name} — Cast Workshop Package

## Contents
- ${slug}-source.jpg — Source image
- wardrobe/ — ${workshop.outfits.length} outfit variant(s)
- scenes/ — ${workshop.shots.length} scene shot(s)

## How to use

### Kling 3.0 Pro
1. Open Kling → Image to Video
2. Upload any image from this package as the starting frame
3. Describe the action in your prompt

### Runway Gen-4
1. Open Runway → Image to Video
2. Upload any image from this package

### Veo 3.1
1. Open Veo → Image to Video
2. Upload the source or any variant image

## License
Generated by Cast Workshop (castability.ai).
`;
  archive.append(Buffer.from(readme, 'utf-8'), { name: 'README.md' });

  archive.finalize();
  const zipBuffer = await done;

  return new NextResponse(new Uint8Array(zipBuffer), {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${slug}-cast-package.zip"`,
    },
  });
}
