export type TalentSex = 'male' | 'female' | 'nonbinary';
export type TalentRace =
  | 'east-asian'
  | 'south-asian'
  | 'southeast-asian'
  | 'pacific-islander'
  | 'black'
  | 'latino'
  | 'middle-eastern'
  | 'european'
  | 'white'
  | 'indigenous'
  | 'central-asian'
  | 'mixed';
export type TalentAgeRange = 'child' | 'teen' | '20s' | '30s' | '40s' | '50s' | '60s+';
export type TalentBuild = 'slim' | 'athletic' | 'average' | 'stocky' | 'curvy' | 'plus-size';
export type TalentHeight = 'short' | 'average' | 'tall';
export type TalentStyle = 'realistic' | 'anime' | 'cartoon' | '3d-cgi' | 'stylized';
export interface PriceOption {
  name: string;
  price: string;
  amount: number;
}

export interface Talent {
  id: number;
  name: string;
  slug: string;
  vibe: string;
  img: string;
  imgThumbnail?: string;
  imgHistory?: string[];
  gallery?: string[];
  referenceSheetUrl?: string;
  refSheetThumbnail?: string;
  referenceSheetHistory?: string[];
  // Core attributes
  sex: TalentSex;
  race: TalentRace[];
  ethnicity?: string;
  age?: number;
  ageRange: TalentAgeRange;
  build: TalentBuild;
  height: TalentHeight;
  style: TalentStyle;
  prices: PriceOption[];
  createdAt?: string;
  exclusive?: boolean;
  exclusiveDisabled?: boolean;
  hidden?: boolean;
  featured?: boolean;
  autoGenerated?: boolean;
}

// ── Label maps for display ──────────────────────────────────────────

export const SEX_LABELS: Record<TalentSex, string> = {
  male: 'Male',
  female: 'Female',
  nonbinary: 'Non-binary',
};

export const RACE_LABELS: Record<TalentRace, string> = {
  'east-asian': 'East Asian',
  'south-asian': 'South Asian',
  'southeast-asian': 'Southeast Asian',
  'pacific-islander': 'Pacific Islander',
  'black': 'Black',
  'latino': 'Latino / Hispanic',
  'middle-eastern': 'Middle Eastern',
  'european': 'European',
  'white': 'White',
  'indigenous': 'Indigenous',
  'central-asian': 'Central Asian',
  'mixed': 'Mixed Heritage',
};

export const AGE_LABELS: Record<TalentAgeRange, string> = {
  child: 'Child',
  teen: 'Teen',
  '20s': '20s',
  '30s': '30s',
  '40s': '40s',
  '50s': '50s',
  '60s+': '60s+',
};

export const BUILD_LABELS: Record<TalentBuild, string> = {
  slim: 'Slim',
  athletic: 'Athletic',
  average: 'Average',
  stocky: 'Stocky',
  curvy: 'Curvy',
  'plus-size': 'Plus-size',
};

export const HEIGHT_LABELS: Record<TalentHeight, string> = {
  short: 'Short',
  average: 'Average',
  tall: 'Tall',
};

export const STYLE_LABELS: Record<TalentStyle, string> = {
  realistic: 'Realistic',
  anime: 'Anime',
  cartoon: 'Cartoon',
  '3d-cgi': '3D / CGI',
  stylized: 'Stylized',
};

// ── Image helpers ────────────────────────────────────────────────────

/** Append a width parameter to a /api/media URL for on-the-fly resizing */
export function thumbUrl(url: string, width: number): string {
  if (!url || !url.startsWith('/api/media')) return url;
  const sep = url.includes('?') ? '&' : '?';
  return `${url}${sep}w=${width}`;
}

// ── Filter config (used by roster UI) ────────────────────────────────

export const FILTER_GROUPS = [
  {
    key: 'sex' as const,
    label: 'Sex',
    options: Object.entries(SEX_LABELS).filter(([value]) => value !== 'nonbinary').map(([value, label]) => ({ value, label })),
  },
  {
    key: 'race' as const,
    label: 'Race',
    options: Object.entries(RACE_LABELS).map(([value, label]) => ({ value, label })),
  },
  {
    key: 'ageRange' as const,
    label: 'Age Range',
    options: Object.entries(AGE_LABELS).map(([value, label]) => ({ value, label })),
  },
  {
    key: 'build' as const,
    label: 'Build',
    options: Object.entries(BUILD_LABELS).map(([value, label]) => ({ value, label })),
  },
  {
    key: 'height' as const,
    label: 'Height',
    options: Object.entries(HEIGHT_LABELS).map(([value, label]) => ({ value, label })),
  },
  {
    key: 'style' as const,
    label: 'Style',
    options: Object.entries(STYLE_LABELS).map(([value, label]) => ({ value, label })),
  },
] as const;

export type FilterKey = typeof FILTER_GROUPS[number]['key'];
export type ActiveFilters = Partial<Record<FilterKey, string[]>>;

// ── Filtering logic ───────────────────────────────────────────────────

export function filterTalent(talents: Talent[], filters: ActiveFilters): Talent[] {
  return talents.filter((t) => {
    for (const [key, selected] of Object.entries(filters) as [FilterKey, string[]][]) {
      if (!selected || selected.length === 0) continue;
      const val = t[key];
      if (Array.isArray(val)) {
        if (!selected.some((s) => val.includes(s as never))) return false;
      } else {
        if (!selected.includes(val as string)) return false;
      }
    }
    return true;
  });
}

// ── Talent data ───────────────────────────────────────────────────────

export const talents: Talent[] = [
  {
    id: 1,
    name: "Elara Voss",
    slug: "elara-voss",
    vibe: "Cool-headed corporate exec with a hidden edge. Sharp suits, sharper wit.",
    img: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80",
    sex: 'female',
    race: ['white'],
    ageRange: '30s',
    build: 'slim',
    height: 'tall',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 2,
    name: "Marco Drev",
    slug: "marco-drev",
    vibe: "Rugged field operative. Weathered, world-weary, and completely reliable.",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80",
    sex: 'male',
    race: ['white'],
    ageRange: '40s',
    build: 'athletic',
    height: 'tall',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 3,
    name: "Nova Sinclair",
    slug: "nova-sinclair",
    vibe: "Gen-Z hacker with an aesthetic. Neon-lit rooms, effortless confidence.",
    img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80",
    sex: 'female',
    race: ['white', 'mixed'],
    ageRange: '20s',
    build: 'slim',
    height: 'average',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 4,
    name: "Viktor Hale",
    slug: "viktor-hale",
    vibe: "The one you don't see coming. Charming surface, calculated interior.",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
    sex: 'male',
    race: ['white'],
    ageRange: '40s',
    build: 'average',
    height: 'tall',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 5,
    name: "Sera Moss",
    slug: "sera-moss",
    vibe: "Small-town idealist turned big-city disruptor. Raw, relatable, magnetic.",
    img: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&q=80",
    sex: 'female',
    race: ['black', 'mixed'],
    ageRange: '20s',
    build: 'average',
    height: 'average',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 6,
    name: "Cain Rhoades",
    slug: "cain-rhoades",
    vibe: "Ex-military turned morally grey antihero. Stoic, scarred, survivalist.",
    img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
    sex: 'male',
    race: ['white'],
    ageRange: '30s',
    build: 'athletic',
    height: 'tall',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 7,
    name: "Lyra Chen",
    slug: "lyra-chen",
    vibe: "Brilliant scientist who skipped social cues entirely. Awkward genius energy.",
    img: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&q=80",
    sex: 'female',
    race: ['east-asian'],
    ageRange: '30s',
    build: 'slim',
    height: 'short',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 8,
    name: "Axel Dunn",
    slug: "axel-dunn",
    vibe: "Silver-tongued politician with something to hide. Power suit, perfect teeth.",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&q=80",
    sex: 'male',
    race: ['white'],
    ageRange: '50s',
    build: 'average',
    height: 'average',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 9,
    name: "Zara Nile",
    slug: "zara-nile",
    vibe: "Fearless investigative journalist. Sees through everyone. No filter.",
    img: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80",
    sex: 'female',
    race: ['black'],
    ageRange: '30s',
    build: 'athletic',
    height: 'tall',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 10,
    name: "Jasper Reid",
    slug: "jasper-reid",
    vibe: "Charming everyman navigating extraordinary circumstances. You root for him.",
    img: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&q=80",
    sex: 'male',
    race: ['white'],
    ageRange: '20s',
    build: 'average',
    height: 'average',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 11,
    name: "Mira Sol",
    slug: "mira-sol",
    vibe: "Free-spirited wanderer with depth. Warm, artistic, quietly wise.",
    img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=80",
    sex: 'female',
    race: ['latino'],
    ageRange: '20s',
    build: 'slim',
    height: 'average',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
  {
    id: 12,
    name: "Omar Steele",
    slug: "omar-steele",
    vibe: "Legendary mentor figure. Every word lands. Every scene, he owns.",
    img: "https://images.unsplash.com/photo-1542178243-bc20204b769f?w=600&q=80",
    sex: 'male',
    race: ['black'],
    ageRange: '60s+',
    build: 'stocky',
    height: 'tall',
    style: 'realistic',
    prices: [
      { name: "Single Project", price: "$50", amount: 50 },
      { name: "Studio License", price: "$250", amount: 250 },
      { name: "Exclusive Rights", price: "$1000", amount: 1000 },
    ],
  },
];
