/**
 * Single source of truth for the video tools Cast hands off to.
 *
 * Used by the in-app handoff UI (DownloadModal) and the README inside the
 * exported ZIP — keep the per-tool steps here so the two never drift.
 */

export interface WorkshopTool {
  /** Stable identifier (lowercase, no spaces). */
  slug: 'kling' | 'higgsfield' | 'artlist';
  /** Display name. */
  name: string;
  /** Short tagline shown next to the name in handoff buttons. */
  tagline: string;
  /** URL we open in a new tab when the user clicks the handoff button.
   *  Prefer the tool's image-to-video entry page; fall back to the homepage
   *  if a deep-link path isn't reliable. */
  url: string;
  /** Numbered steps shown both in-modal and inside the ZIP README. Keep
   *  short — these are the same instructions in both surfaces. */
  steps: string[];
  /** Optional path to a logo file under /public/logos/. When the file is
   *  present, the SendToVideoFooter renders <img>; when absent, it falls
   *  back to a brand-colored text-mark card. */
  logo?: string;
  /** Brand accent color (hex). Used for the left edge of the card and the
   *  fallback text-mark when no logo file exists. */
  accent: string;
}

export const WORKSHOP_TOOLS: WorkshopTool[] = [
  {
    slug: 'kling',
    name: 'Kling',
    tagline: 'Image to Video',
    url: 'https://app.klingai.com/global/image-to-video/frame-mode',
    logo: '/logos/kling.png',
    accent: '#000000',
    steps: [
      'Open Kling and pick Image-to-Video.',
      'Upload the profile photo (or paste the URL we just copied) as the starting frame.',
      'Write your scene prompt — describe the action, camera move, and setting.',
      'For multi-shot consistency, reuse the same profile across each shot.',
    ],
  },
  {
    slug: 'higgsfield',
    name: 'Higgsfield',
    tagline: 'Cinematic AI motion',
    url: 'https://higgsfield.ai/create',
    logo: '/logos/higgsfield.png',
    accent: '#C5FF1A',
    steps: [
      'Open Higgsfield and pick Image-to-Video.',
      'Upload the profile photo (or paste the URL we just copied).',
      'Write your scene prompt and pick a motion preset if you want one.',
      'For consistency across shots, use the same profile each time.',
    ],
  },
  {
    slug: 'artlist',
    name: 'Artlist',
    tagline: 'Brand-safe AI video',
    url: 'https://artlist.io/ai/video-generator',
    logo: '/logos/artlist.jpg',
    accent: '#F5D000',
    steps: [
      'Open Artlist and pick AI Video → Image-to-Video.',
      'Upload the profile photo (or paste the URL we just copied).',
      'Write your scene prompt.',
      'Reuse the same profile across every shot to keep the character consistent.',
    ],
  },
];

/** Build the README that ships inside the export ZIP. Same steps as the
 *  in-app handoff, so the two can never drift. */
export function buildPackageReadme(opts: {
  characterName: string;
  filenamePrefix: string;
  hasReferenceSheet: boolean;
  outfitCount: number;
  shotCount: number;
}): string {
  const { characterName, filenamePrefix, hasReferenceSheet, outfitCount, shotCount } = opts;
  const toolSections = WORKSHOP_TOOLS.map((t) => {
    const numbered = t.steps.map((s, i) => `${i + 1}. ${s}`).join('\n');
    return `### ${t.name}\n${numbered}\n`;
  }).join('\n');

  return `# ${characterName} — Cast Workshop Package

## Contents
- ${filenamePrefix}-source.jpg — Profile photo (drop this into your video tool)
${hasReferenceSheet ? `- ${filenamePrefix}-reference-sheet.jpg — 4K 8-panel reference sheet (use as visual reference for new angles)\n` : ''}- wardrobe/ — ${outfitCount} outfit variant(s)
- scenes/ — ${shotCount} scene shot(s)

## How to use this package

The profile photo is your primary handoff. Upload it as the starting frame in any
image-to-video tool. The reference sheet is for *you* — keep it open as a visual
guide when writing prompts ("front-facing, three-quarter right, etc.").

${toolSections}
## License
Generated by Cast (castability.ai).
`;
}
