'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { useSearchParams } from 'next/navigation';
import { toast } from 'sonner';
import { CustomCharacterDraft } from '@/lib/custom-characters.server';
import DescribeStep from './DescribeStep';
import PreviewStep from './PreviewStep';
import PaymentStep from './PaymentStep';
import CompleteStep from './CompleteStep';
import DraftsList from './DraftsList';

type Step = 'describe' | 'preview' | 'payment' | 'complete';

interface PreviewGenState {
  generating: boolean;
  error: string;
}

interface FullGenState {
  generating: boolean;
  error: string;
}

export default function CreateClient() {
  const searchParams = useSearchParams();
  const isPurchaseReturn = searchParams.get('credits') === 'purchased';
  const [step, setStep] = useState<Step>(isPurchaseReturn ? 'payment' : 'describe');
  const [drafts, setDrafts] = useState<CustomCharacterDraft[]>([]);
  const [currentDraft, setCurrentDraft] = useState<CustomCharacterDraft | null>(null);
  const [credits, setCredits] = useState(0);
  const [loading, setLoading] = useState(true);

  // Track preview generation state per draft ID — survives draft switching
  const [previewGenStates, setPreviewGenStates] = useState<Record<string, PreviewGenState>>({});
  const [fullGenStates, setFullGenStates] = useState<Record<string, FullGenState>>({});
  const autoGeneratedRef = useRef<Set<string>>(new Set());
  const fullGenTriggeredRef = useRef<Set<string>>(new Set());
  const purchaseHandledRef = useRef(false);
  const initialLoadDoneRef = useRef(false);

  const fetchDrafts = useCallback(async () => {
    const res = await fetch('/api/create/drafts');
    if (res.ok) setDrafts(await res.json());
  }, []);

  const fetchCredits = useCallback(async () => {
    const res = await fetch('/api/create/credits');
    if (res.ok) {
      const data = await res.json();
      setCredits(data.credits);
    }
  }, []);

  useEffect(() => {
    if (initialLoadDoneRef.current) return;
    initialLoadDoneRef.current = true;

    const restoreDraftId = searchParams.get('draft');

    Promise.all([
      fetch('/api/create/drafts').then((r) => r.ok ? r.json() : []),
      fetchCredits(),
    ]).then(([loadedDrafts]) => {
      setDrafts(loadedDrafts);
      // Only auto-select a draft if a specific draft ID is in the URL (e.g. refresh mid-flow)
      if (!isPurchaseReturn && restoreDraftId && loadedDrafts.length > 0) {
        const target = loadedDrafts.find((d: { id: string }) => d.id === restoreDraftId);
        if (target) {
          setCurrentDraft(target);
          if (target.status === 'complete' || target.status === 'generating') {
            setStep('complete');
            // If status is generating but has no assets, re-trigger (only once via ref guard)
            if (target.status === 'generating' && !target.profileImageUrl && !target.referenceSheetUrl) {
              generateFull(target.id);
            }
          } else if (target.status === 'preview' || target.status === 'paid') setStep('payment');
          else if (target.previewImageUrl) setStep('preview');
          else setStep('describe');
        }
      }
    }).finally(() => setLoading(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // --- Full package generation logic ---
  const generateFull = useCallback(async (draftId: string) => {
    if (fullGenTriggeredRef.current.has(draftId)) return;
    fullGenTriggeredRef.current.add(draftId);

    setFullGenStates((prev) => ({ ...prev, [draftId]: { generating: true, error: '' } }));

    try {
      const res = await fetch('/api/create/generate-full', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ draftId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);

      const updatedDraft = {
        status: 'complete' as const,
        profileImageUrl: data.profileImageUrl,
        profileThumbnailUrl: data.profileThumbnailUrl,
        referenceSheetUrl: data.referenceSheetUrl,
        referenceSheetThumbnailUrl: data.referenceSheetThumbnailUrl,
        completedAt: new Date().toISOString(),
      };

      setCurrentDraft((prev) =>
        prev?.id === draftId ? { ...prev, ...updatedDraft } : prev
      );
      setDrafts((prev) =>
        prev.map((d) => d.id === draftId ? { ...d, ...updatedDraft } : d)
      );
      setFullGenStates((prev) => ({ ...prev, [draftId]: { generating: false, error: '' } }));
      setCredits((c) => Math.max(0, c - 1));
      fetchCredits();
    } catch (err) {
      fullGenTriggeredRef.current.delete(draftId);
      setFullGenStates((prev) => ({
        ...prev,
        [draftId]: { generating: false, error: err instanceof Error ? err.message : 'Generation failed' },
      }));
    }
  }, [fetchCredits]);

  // Handle credit purchase return — confirm and auto-generate
  useEffect(() => {
    const purchased = searchParams.get('credits');
    const sessionId = searchParams.get('session_id');
    const draftId = searchParams.get('draft');

    if (purchased === 'purchased' && sessionId && !purchaseHandledRef.current) {
      purchaseHandledRef.current = true;

      (async () => {
        try {
          // Confirm credits with Stripe
          const confirmRes = await fetch('/api/create/confirm-credits', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ sessionId }),
          });

          if (confirmRes.ok) {
            const confirmData = await confirmRes.json();
            setCredits(confirmData.credits);
          } else {
            const err = await confirmRes.json();
            toast.error(err.error || 'Failed to confirm purchase');
          }

          // Load draft and go directly to download step + auto-generate
          if (draftId) {
            const draftRes = await fetch(`/api/create/drafts/${draftId}`);
            if (draftRes.ok) {
              const draft = await draftRes.json();
              setCurrentDraft(draft);
              if (draft.status === 'complete') {
                setStep('complete');
              } else {
                setStep('complete');
                generateFull(draft.id);
              }
            }
          }
        } catch {
          toast.error('Something went wrong confirming your purchase');
        } finally {
          window.history.replaceState({}, '', '/create');
        }
      })();
    }
  }, [searchParams, generateFull]);

  // --- Preview generation logic (lives in parent so it survives draft switching) ---

  const generatePreview = useCallback(async (draftId: string) => {
    setPreviewGenStates((prev) => ({ ...prev, [draftId]: { generating: true, error: '' } }));

    try {
      const res = await fetch('/api/create/generate-preview', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ draftId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);

      // Update the draft with new preview data
      setCurrentDraft((prev) =>
        prev?.id === draftId
          ? { ...prev, previewImageUrl: data.previewImageUrl, previewImages: data.previewImages, iterations: data.iterations, status: 'preview' as const }
          : prev
      );
      setDrafts((prev) =>
        prev.map((d) =>
          d.id === draftId
            ? { ...d, previewImageUrl: data.previewImageUrl, previewImages: data.previewImages, iterations: data.iterations, status: 'preview' as const }
            : d
        )
      );
      setPreviewGenStates((prev) => ({ ...prev, [draftId]: { generating: false, error: '' } }));
    } catch (err) {
      setPreviewGenStates((prev) => ({
        ...prev,
        [draftId]: { generating: false, error: err instanceof Error ? err.message : 'Generation failed' },
      }));
    }
  }, []);

  // Auto-generate preview when entering preview step with no image
  useEffect(() => {
    if (step === 'preview' && currentDraft && !currentDraft.previewImageUrl) {
      if (!autoGeneratedRef.current.has(currentDraft.id)) {
        autoGeneratedRef.current.add(currentDraft.id);
        generatePreview(currentDraft.id);
      }
    }
  }, [step, currentDraft, generatePreview]);

  // --- Handlers ---

  const syncDraftToUrl = (draftId: string | null) => {
    const url = new URL(window.location.href);
    if (draftId) url.searchParams.set('draft', draftId);
    else url.searchParams.delete('draft');
    window.history.replaceState({}, '', url.toString());
  };

  const handleNewCharacter = () => {
    setCurrentDraft(null);
    setStep('describe');
    syncDraftToUrl(null);
  };

  const handleSelectDraft = (draft: CustomCharacterDraft) => {
    setCurrentDraft(draft);
    syncDraftToUrl(draft.id);
    const genState = previewGenStates[draft.id];
    const fullState = fullGenStates[draft.id];
    if (fullState?.generating || draft.status === 'generating') {
      setStep('complete');
      // Re-trigger if generation was interrupted (no active state but status=generating and no URLs)
      if (!fullState?.generating && draft.status === 'generating' && !draft.profileImageUrl && !draft.referenceSheetUrl) {
        generateFull(draft.id);
      }
    } else if (genState?.generating) {
      // Draft is mid-generation — show preview step with spinner
      setStep('preview');
    } else if (draft.status === 'complete') {
      setStep('complete');
    } else if (draft.status === 'preview' || draft.status === 'paid') {
      setStep('payment');
    } else {
      setStep('describe');
    }
  };

  const handleDescribeComplete = async (draft: CustomCharacterDraft) => {
    setCurrentDraft(draft);
    syncDraftToUrl(draft.id);
    await fetchDrafts();
    setStep('preview');
  };

  const handleSelectPreviewImage = (url: string) => {
    setCurrentDraft((prev) => {
      if (!prev) return prev;
      // Match the sourceProfileUrl to the selected preview
      const idx = (prev.previewImages ?? []).indexOf(url);
      const matchedSourceUrl = idx >= 0 && prev.sourceProfileUrls?.[idx]
        ? prev.sourceProfileUrls[idx]
        : prev.sourceProfileUrl;
      // Persist selection to server (fire-and-forget outside state updater)
      const draftId = prev.id;
      queueMicrotask(() => {
        fetch(`/api/create/drafts/${draftId}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ previewImageUrl: url, sourceProfileUrl: matchedSourceUrl }),
        });
      });
      return { ...prev, previewImageUrl: url, sourceProfileUrl: matchedSourceUrl };
    });
  };

  const handlePreviewComplete = (draft: CustomCharacterDraft) => {
    setCurrentDraft(draft);
    // Persist the selected preview to the server
    fetch(`/api/create/drafts/${draft.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ previewImageUrl: draft.previewImageUrl, sourceProfileUrl: draft.sourceProfileUrl }),
    });
    setStep('payment');
  };

  const handlePaymentComplete = (draft: CustomCharacterDraft) => {
    setCurrentDraft(draft);
    setStep('complete');
    // If the PaymentStep already called generate-full and returned data, draft will have the URLs
    // If not (e.g. credits path), trigger generation
    if (!draft.profileImageUrl || !draft.referenceSheetUrl) {
      generateFull(draft.id);
    } else {
      setCredits((c) => Math.max(0, c - 1));
      fetchDrafts();
      fetchCredits();
    }
  };

  const handleDeleteDraft = async (draftId: string) => {
    await fetch(`/api/create/drafts/${draftId}`, { method: 'DELETE' });
    if (currentDraft?.id === draftId) {
      setCurrentDraft(null);
      setStep('describe');
    }
    await fetchDrafts();
    toast('Draft deleted');
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 pt-24 flex items-center justify-center">
        <div className="animate-pulse text-gray-400">
          {isPurchaseReturn ? 'Confirming your purchase...' : 'Loading...'}
        </div>
      </div>
    );
  }

  const currentGenState = currentDraft ? previewGenStates[currentDraft.id] : undefined;
  const currentFullGenState = currentDraft ? fullGenStates[currentDraft.id] : undefined;

  return (
    <div className="min-h-screen bg-gray-50 pt-20">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-widest text-indigo-500 mb-1">Create</p>
            <h1 className="text-3xl font-black tracking-tighter text-black">Create Your Character</h1>
          </div>
          <div className="bg-indigo-50 text-indigo-600 text-sm font-bold px-4 py-2 rounded-full">
            {credits} character{credits !== 1 ? 's' : ''} remaining
          </div>
        </div>

        <div className="lg:flex lg:gap-8">
          {/* Sidebar — drafts */}
          <aside className="hidden lg:block w-64 flex-shrink-0">
            <DraftsList
              drafts={drafts}
              currentDraftId={currentDraft?.id ?? null}
              onSelect={handleSelectDraft}
              onDelete={handleDeleteDraft}
              onNew={handleNewCharacter}
            />
          </aside>

          {/* Main content */}
          <div className="flex-1 min-w-0">
            {/* Step indicator */}
            <div className="flex items-center gap-1 sm:gap-2 mb-6">
              {(['describe', 'preview', 'payment', 'complete'] as Step[]).map((s, i) => {
                // Determine the furthest step the draft has reached
                const stepOrder: Step[] = ['describe', 'preview', 'payment', 'complete'];
                const currentIdx = stepOrder.indexOf(step);
                const targetIdx = i;
                let maxReachable = 0; // describe is always reachable
                if (currentDraft) {
                  if (currentDraft.previewImageUrl) maxReachable = 1; // can go to preview
                  if (currentDraft.status === 'preview' || currentDraft.status === 'paid' || currentDraft.status === 'complete' || currentDraft.status === 'generating') maxReachable = 2; // can go to payment
                  if (currentDraft.status === 'complete' || currentDraft.status === 'generating') maxReachable = 3; // can go to download
                }
                // Also allow going back to any step before current
                const canNavigate = currentDraft && targetIdx <= Math.max(currentIdx, maxReachable) && s !== step;
                const isPast = currentIdx > targetIdx;

                return (
                  <div key={s} className="flex items-center gap-1 sm:gap-2">
                    <button
                      type="button"
                      disabled={!canNavigate}
                      onClick={() => canNavigate && setStep(s)}
                      className={`w-6 h-6 sm:w-7 sm:h-7 rounded-full flex items-center justify-center text-[10px] sm:text-xs font-bold flex-shrink-0 transition-colors ${
                        step === s ? 'bg-indigo-500 text-white' :
                        isPast ? 'bg-indigo-100 text-indigo-600 hover:bg-indigo-200 cursor-pointer' :
                        canNavigate ? 'bg-indigo-100 text-indigo-600 hover:bg-indigo-200 cursor-pointer' :
                        'bg-gray-100 text-gray-400'
                      } ${canNavigate ? '' : 'cursor-default'}`}
                    >
                      {i + 1}
                    </button>
                    <button
                      type="button"
                      disabled={!canNavigate}
                      onClick={() => canNavigate && setStep(s)}
                      className={`text-[11px] sm:text-xs font-medium capitalize whitespace-nowrap transition-colors ${
                        step === s ? 'text-black' :
                        canNavigate ? 'text-gray-500 hover:text-black cursor-pointer' :
                        'text-gray-400'
                      } ${canNavigate ? '' : 'cursor-default'}`}
                    >
                      {s === 'complete' ? 'Download' : s}
                    </button>
                    {i < 3 && <div className="flex-1 min-w-3 sm:min-w-8 h-px bg-gray-200" />}
                  </div>
                );
              })}
            </div>

            {/* Steps */}
            {step === 'describe' && (
              <DescribeStep
                draft={currentDraft}
                onComplete={handleDescribeComplete}
              />
            )}
            {step === 'preview' && currentDraft && (
              <PreviewStep
                draft={currentDraft}
                isGenerating={currentGenState?.generating ?? false}
                generationError={currentGenState?.error ?? ''}
                onGenerate={() => generatePreview(currentDraft.id)}
                onSelectPreview={handleSelectPreviewImage}
                onComplete={handlePreviewComplete}
                onBack={() => setStep('describe')}
              />
            )}
            {step === 'payment' && currentDraft && (
              <PaymentStep
                draft={currentDraft}
                credits={credits}
                onComplete={handlePaymentComplete}
                onBack={() => setStep('preview')}
              />
            )}
            {step === 'complete' && currentDraft && (
              <CompleteStep
                draft={currentDraft}
                generating={currentFullGenState?.generating}
                generationError={currentFullGenState?.error}
                onRetry={() => {
                  fullGenTriggeredRef.current.delete(currentDraft.id);
                  generateFull(currentDraft.id);
                }}
                onNewCharacter={handleNewCharacter}
              />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
