/**
 * Auto-Cast Agent — Automated character creation for Cast marketplace
 *
 * Usage:
 *   npx tsx scripts/auto-cast.ts              # generate dailyTarget characters
 *   npx tsx scripts/auto-cast.ts --count 5    # generate 5 characters
 *   npx tsx scripts/auto-cast.ts --dry-run    # show what would be generated
 *   npx tsx scripts/auto-cast.ts --visible    # create as visible (skip review)
 */

import 'dotenv/config';
import { readCharacters, writeCharacters, nextId } from '../lib/characters.server';
import { loadStrategy, analyzeRosterGaps, isDuplicate, computeRosterStats, DemographicSlot } from '../lib/casting-strategy';
import { describeCharacterFromSlot, validateAttributes, DescribeResult } from '../lib/auto-describe';
import { generateBoth, GenerateMeta } from '../lib/generation.server';
import { Talent, TalentRace } from '../lib/talent';
import { Resend } from 'resend';

// ── CLI args ─────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const visible = args.includes('--visible');
const countIdx = args.indexOf('--count');
const countOverride = countIdx >= 0 ? parseInt(args[countIdx + 1], 10) : undefined;

// ── Types ────────────────────────────────────────────────────────────────

interface CreatedCharacter {
  id: number;
  name: string;
  slug: string;
  description: string;
  sex: string;
  race: string[];
  ethnicity?: string;
  age?: number;
  ageRange: string;
  archetype: string;
  profileUrl: string;
  profileThumbUrl: string;
  refSheetUrl: string;
  claudeCost: number;
  imageCost: number;
  durationMs: number;
}

interface BatchResult {
  created: CreatedCharacter[];
  failures: { slot: DemographicSlot; error: string }[];
  totalClaudeCost: number;
  totalImageCost: number;
  totalDurationMs: number;
}

// ── Main ─────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const strategy = loadStrategy();
  const count = countOverride ?? strategy.dailyTarget;

  console.log(`\n🎬 Auto-Cast Agent`);
  console.log(`   Target: ${count} characters | Dry run: ${dryRun} | Visible: ${visible}\n`);

  // Read current roster
  const characters = await readCharacters();
  console.log(`   Current roster: ${characters.length} characters (${characters.filter(c => !c.hidden).length} visible)\n`);

  // Analyze gaps and generate slots
  const slots = analyzeRosterGaps(characters, strategy, count);

  console.log(`📋 Demographic slots to fill:`);
  for (let i = 0; i < slots.length; i++) {
    const s = slots[i];
    console.log(`   ${i + 1}. ${s.sex} | ${s.race} | ${s.ageRange} | ${s.build} | ${s.archetype}`);
  }
  console.log();

  if (dryRun) {
    console.log('🏁 Dry run complete — no characters created.\n');
    const stats = computeRosterStats(characters);
    console.log(`📊 Roster stats:`);
    console.log(`   Total: ${stats.total} | Visible: ${stats.visible} | Hidden: ${stats.hidden} | Auto: ${stats.autoGenerated}`);
    console.log(`   Sex:`, stats.sex);
    console.log(`   Race:`, stats.race);
    console.log(`   Age:`, stats.ageRange);
    return;
  }

  // Generate characters
  const result: BatchResult = {
    created: [],
    failures: [],
    totalClaudeCost: 0,
    totalImageCost: 0,
    totalDurationMs: 0,
  };

  let currentCharacters = characters;

  for (let i = 0; i < slots.length; i++) {
    const slot = slots[i];
    const startTime = Date.now();
    console.log(`\n━━━ Character ${i + 1}/${slots.length} ━━━`);
    console.log(`   Slot: ${slot.sex} | ${slot.race} | ${slot.ageRange} | ${slot.build} | ${slot.archetype}`);

    try {
      // Step 1: Generate description (with retries for duplicates and validation)
      let describe: DescribeResult | null = null;
      const existingNames = currentCharacters.map(c => c.name);

      for (let attempt = 0; attempt < 3; attempt++) {
        console.log(`   📝 Describing character (attempt ${attempt + 1})...`);
        const candidate = await describeCharacterFromSlot(slot, existingNames);

        if (isDuplicate(candidate.name, candidate.slug, currentCharacters)) {
          console.log(`   ⚠️  Duplicate detected: "${candidate.name}" — retrying`);
          continue;
        }

        if (!validateAttributes(candidate, slot)) {
          console.log(`   ⚠️  Demographics mismatch — retrying`);
          continue;
        }

        describe = candidate;
        break;
      }

      if (!describe) {
        throw new Error('Failed to generate unique, valid description after 3 attempts');
      }

      console.log(`   ✅ ${describe.name} — ${describe.description.slice(0, 80)}...`);
      console.log(`   💰 Claude cost: $${describe.claudeCost.toFixed(4)}`);
      result.totalClaudeCost += describe.claudeCost;

      // Step 2: Generate images (profile + reference sheet)
      console.log(`   🖼  Generating profile + reference sheet...`);
      const id = nextId(currentCharacters);
      const meta: GenerateMeta = {
        characterId: id,
        characterName: describe.name,
        characterSlug: describe.slug,
        claudeCost: describe.claudeCost,
      };

      const { profile, refSheet, profileThumbUrl, refSheetThumbUrl } = await generateBoth(
        describe.description,
        describe.slug,
        meta,
      );

      const imageCost = profile.cost + refSheet.cost;
      result.totalImageCost += imageCost;
      console.log(`   ✅ Images generated — profile: ${profile.provider}, refsheet: ${refSheet.provider}`);
      console.log(`   💰 Image cost: $${imageCost.toFixed(4)}`);

      // Step 3: Build and save character
      const attrs = describe.attributes;
      const newCharacter: Talent & { autoGenerated: boolean } = {
        id,
        name: describe.name,
        slug: describe.slug,
        vibe: describe.description,
        img: profile.url,
        imgThumbnail: profileThumbUrl,
        referenceSheetUrl: refSheet.url,
        refSheetThumbnail: refSheetThumbUrl,
        sex: attrs.sex as Talent['sex'],
        race: (Array.isArray(attrs.race) ? attrs.race : [slot.race]) as TalentRace[],
        ethnicity: attrs.ethnicity,
        age: attrs.age,
        ageRange: attrs.ageRange as Talent['ageRange'],
        build: attrs.build as Talent['build'],
        height: (attrs.height || 'average') as Talent['height'],
        style: (attrs.style || 'realistic') as Talent['style'],
        prices: [
          { name: 'Single Project', price: '$50', amount: 50 },
          { name: 'Studio License', price: '$250', amount: 250 },
          { name: 'Exclusive Rights', price: '$1000', amount: 1000 },
        ],
        createdAt: new Date().toISOString(),
        hidden: !visible && strategy.hiddenByDefault,
        autoGenerated: true,
      };

      // Re-read to avoid race conditions, then merge
      currentCharacters = await readCharacters();
      currentCharacters.push(newCharacter);
      await writeCharacters(currentCharacters);

      const durationMs = Date.now() - startTime;
      result.totalDurationMs += durationMs;

      const created: CreatedCharacter = {
        id,
        name: describe.name,
        slug: describe.slug,
        description: describe.description,
        sex: attrs.sex,
        race: Array.isArray(attrs.race) ? attrs.race : [slot.race],
        ethnicity: attrs.ethnicity,
        age: attrs.age,
        ageRange: attrs.ageRange,
        archetype: slot.archetype,
        profileUrl: profile.url,
        profileThumbUrl,
        refSheetUrl: refSheet.url,
        claudeCost: describe.claudeCost,
        imageCost,
        durationMs,
      };

      result.created.push(created);
      console.log(`   ✅ Saved as ID ${id} (${durationMs / 1000}s)`);

    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(`   ❌ Failed: ${message}`);
      result.failures.push({ slot, error: message });
    }
  }

  // ── Summary ──────────────────────────────────────────────────────────

  console.log(`\n${'━'.repeat(50)}`);
  console.log(`🎬 Auto-Cast Complete`);
  console.log(`   Created: ${result.created.length}/${slots.length}`);
  console.log(`   Failures: ${result.failures.length}`);
  console.log(`   Total Claude cost: $${result.totalClaudeCost.toFixed(4)}`);
  console.log(`   Total image cost: $${result.totalImageCost.toFixed(4)}`);
  console.log(`   Total cost: $${(result.totalClaudeCost + result.totalImageCost).toFixed(4)}`);
  console.log(`   Total time: ${(result.totalDurationMs / 1000).toFixed(1)}s`);

  if (result.created.length > 0) {
    console.log(`\n   Characters created:`);
    for (const c of result.created) {
      console.log(`     - ${c.name} (${c.sex}, ${c.race.join('/')}, ${c.ageRange}, ${c.archetype})`);
    }
  }

  if (result.failures.length > 0) {
    console.log(`\n   Failures:`);
    for (const f of result.failures) {
      console.log(`     - ${f.slot.sex}/${f.slot.race}/${f.slot.ageRange}: ${f.error}`);
    }
  }

  // ── Send email report ────────────────────────────────────────────────

  if (result.created.length > 0 && process.env.RESEND_API_KEY) {
    await sendReport(result, currentCharacters);
  }

  console.log();
}

// ── Email report ─────────────────────────────────────────────────────────

async function sendReport(result: BatchResult, characters: Talent[]): Promise<void> {
  try {
    const resend = new Resend(process.env.RESEND_API_KEY);
    const stats = computeRosterStats(characters);
    const date = new Date().toISOString().slice(0, 10);
    const baseUrl = 'https://www.castability.ai';

    const characterRows = result.created.map((c) => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #eee;">
          <img src="${baseUrl}${c.profileThumbUrl}" alt="${c.name}" width="60" height="80" style="border-radius:6px;object-fit:cover;" />
        </td>
        <td style="padding:8px;border-bottom:1px solid #eee;">
          <strong>${c.name}</strong><br/>
          <span style="color:#666;font-size:13px;">${c.sex}, ${c.race.join('/')}, ${c.ageRange}${c.age ? ` (${c.age})` : ''}</span><br/>
          <span style="color:#888;font-size:12px;">${c.archetype}</span>
        </td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:center;">
          <a href="${baseUrl}/characters/${c.slug}" style="color:#6366f1;font-size:13px;">View</a>
        </td>
      </tr>
    `).join('');

    const totalCost = result.totalClaudeCost + result.totalImageCost;

    const html = `
      <div style="font-family:sans-serif;max-width:600px;margin:0 auto;">
        <h2 style="color:#111;">Auto-Cast Report — ${date}</h2>
        <p style="color:#666;">
          <strong>${result.created.length}</strong> characters created
          ${result.failures.length > 0 ? ` · <span style="color:#ef4444;">${result.failures.length} failed</span>` : ''}
          · Total cost: <strong>$${totalCost.toFixed(2)}</strong>
          · Time: ${(result.totalDurationMs / 1000 / 60).toFixed(1)} min
        </p>

        <table style="width:100%;border-collapse:collapse;margin:16px 0;">
          <thead>
            <tr style="background:#f9fafb;">
              <th style="padding:8px;text-align:left;font-size:12px;color:#888;width:70px;">Photo</th>
              <th style="padding:8px;text-align:left;font-size:12px;color:#888;">Character</th>
              <th style="padding:8px;text-align:center;font-size:12px;color:#888;width:60px;">Link</th>
            </tr>
          </thead>
          <tbody>
            ${characterRows}
          </tbody>
        </table>

        <h3 style="color:#333;margin-top:24px;">Cost Breakdown</h3>
        <table style="font-size:14px;color:#555;">
          <tr><td style="padding:4px 16px 4px 0;">Claude (Opus):</td><td>$${result.totalClaudeCost.toFixed(4)}</td></tr>
          <tr><td style="padding:4px 16px 4px 0;">Image generation:</td><td>$${result.totalImageCost.toFixed(4)}</td></tr>
          <tr><td style="padding:4px 16px 4px 0;font-weight:bold;">Total:</td><td style="font-weight:bold;">$${totalCost.toFixed(4)}</td></tr>
        </table>

        <h3 style="color:#333;margin-top:24px;">Roster Snapshot</h3>
        <p style="font-size:14px;color:#555;">
          Total: ${stats.total} · Visible: ${stats.visible} · Hidden: ${stats.hidden} · Auto-generated: ${stats.autoGenerated}
        </p>

        <p style="margin-top:24px;font-size:12px;color:#999;">
          Sent by Cast Auto-Cast Agent · <a href="${baseUrl}/admin/dashboard" style="color:#6366f1;">Open Admin Dashboard</a>
        </p>
      </div>
    `;

    await resend.emails.send({
      from: 'no-reply@castability.ai',
      to: 'admin@castability.ai',
      subject: `Auto-Cast Report — ${date} — ${result.created.length} characters created`,
      html,
    });

    console.log(`\n   📧 Report emailed to admin@castability.ai`);
  } catch (err) {
    console.error(`   ⚠️  Failed to send email report:`, err instanceof Error ? err.message : err);
  }
}

// ── Run ──────────────────────────────────────────────────────────────────

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
